version: "3.1"

services:
  db:
    image: postgres:14
    container_name: sql_practice_db
    ports:
      - "5432:5432"
    volumes:
      - sql-practice-db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sql_practice

volumes:
  sql-practice-db-store:
